"""password hashing

Revision ID: 0273e21604be
Revises: 2c184156f73a
Create Date: 2022-05-17 11:30:54.696883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0273e21604be'
down_revision = '2c184156f73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
